spring:
       datasource:
                   url: jdbc:mysql://10.0.17.12:3306/xyqbdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Shanghai&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
                   username: root
                   password: fintech
                   driverClassName: com.mysql.cj.jdbc.Driver
server:
      port: 80